//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backofficev2
{
    using System;
    using System.Collections.Generic;
    
    public partial class img_peca
    {
        public int ID { get; set; }
        public int id_conjunto_pecas { get; set; }
        public byte[] conteudo_arquivo { get; set; }
        public short peca_num_cima { get; set; }
        public short peca_num_abaixo { get; set; }
        public string nome_arquivo { get; set; }
    
        public virtual conj_img_pecas conj_img_pecas { get; set; }
    }
}
